### ISSUE TITLE
Network changes cause the service to fail

### ISSUE THREAD

**Issue by TimZolleis** [triargos/slack-alert#9]
On some network changes, a DNS timeout will occur with the following error:
![image](https://github.com/triargos/slack-alert/assets/95548013/54f2d30f-0508-4c1d-bab9-ee19d51e12ef)

The container needs to be restarted in order to fix this problem.

**Comment by timzolleis** [comment]
Added a custom DNS entry to the docker compose file 

```yaml
...
 slack-alert:
    container_name: slack-alert
    dns:
      - 8.8.8.8
    build:
      context: slack-alert/
    env_file:
      - ./slack-alert/config/.env
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped
...
```
**The issue is to be investigated further**
